In [1]:
import pandas as pd
import numpy as np
a = np.array([10,20,30,40])
b = np.array([2,6,4,8])
print('a  :',a)

a  : [10 20 30 40]


In [2]:
print('a+b :',a+b)

a+b : [12 26 34 48]


In [3]:
prices = np.array([20,30,40,50])
print('Prices :',prices)

Prices : [20 30 40 50]


In [4]:
print('10% Discount :',prices*0.9)
print('18% Discount :',prices*1.18)
print('20 greater :',prices>20)

10% Discount : [18. 27. 36. 45.]
18% Discount : [23.6 35.4 47.2 59. ]
20 greater : [False  True  True  True]


In [5]:
data = np.arange(1,13)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
print(data.reshape(2,2,3))
m1 =data.reshape(4,3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
m1.flatten()
m1.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

### mean median 

In [8]:
marks = np.array([72,85,91,64,78,88,55,93,70,82])
print('marks :',marks)
print('marks :',np.mean(marks))
print('marks :',np.median(marks))
print('marks :',np.std(marks),2)
print('marks :',np.var(marks),2)
print('marks :',np.min(marks))
print('marks :',np.max(marks))
print('marks :',np.sum(marks))
print('marks :',np.percentile(marks,25))
print('marks :',np.percentile(marks,75))
print('marks range :',np.ptp(marks))

marks : [72 85 91 64 78 88 55 93 70 82]
marks : 77.8
marks : 80.0
marks : 11.76265276202609 2
marks : 138.35999999999999 2
marks : 55
marks : 93
marks : 778
marks : 70.5
marks : 87.25
marks range : 38


In [9]:
sales = np.array([
    [100,200,150],
    [130,180,160],
    [140,220,170]
])
print(sales)

[[100 200 150]
 [130 180 160]
 [140 220 170]]


In [10]:
print(np.mean(sales, axis=1))
print(np.mean(sales, axis=0))
print(np.sum(sales, axis=1))
print(np.sum(sales, axis=0))

[150.         156.66666667 176.66666667]
[123.33333333 200.         160.        ]
[450 470 530]
[370 600 480]


In [11]:
cities = np.array(['chennai','mumbai','Delhi','chennai','mumbai'])
print(np.unique(cities))

['Delhi' 'chennai' 'mumbai']
