In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# arrays

1D Arrays

In [ ]:
np.array([20,30,40,50,]) #1D dimensional array

array([20, 30, 40, 50])

2D Arrays

In [4]:
np.array([
    [20,30,40,],
    [50,75,65],
    [25,65,75]
]) #2D dimensional array

array([[20, 30, 40],
       [50, 75, 65],
       [25, 65, 75]])

 3D Arrays

In [14]:
d=np.array([
    [[45,65,35],
    [15,96,75],
    [75,35,85]],

]) #3D dimensional array

In [15]:
print(d.ndim)

3


Arange Fuction

In [9]:
print(np.arange(20))
print(np.arange(1,20,2))
print(np.arange(2,50,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 2  7 12 17 22 27 32 37 42 47]


Linespace fuction

In [12]:
print(np.linspace(25,100,4))

[ 25.  50.  75. 100.]


Array describe

In [22]:
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)
print(d.itemsize)
print(d.nbytes)

3
(1, 3, 3)
9
int64
8
72


##Slicing and Indexing

In [40]:
marks = np.array([75,65,45,95,95,75,65,25,35,45])


In [42]:
print('all marks:',marks)
print('first marks:',marks[0])
print('last marks:',marks[-1])
print('2 gaping marks traversed:',marks[::2])
print('slicicing- 2 to 5:',marks[1:4])
print('reversed marks:',marks[::-1])

all marks: [75 65 45 95 95 75 65 25 35 45]
first marks: 75
last marks: 45
2 gaping marks traversed: [75 45 95 65 35]
slicicing- 2 to 5: [65 45 95]
reversed marks: [45 35 25 65 75 95 95 45 65 75]
